### ISSUE TITLE
FR13 TXT from CSV Orientation For Database

### ISSUE THREAD

**Issue by kevinWayneState** [WSU-4110/Fantasy-Scout#10]
| Data collection accuracy checking |
|---|
|**Goal**:  Format CSV data to be readable in TXT files to be read into database by established algorithms  |
|**Stakeholders**: This process is mainly affecting the development team's capability to read information from prediction sources into the database efficiently|
|**Description**: Powershell ISE formats the input files in the given structure established in sprint 2. The CSV file is selectively loaded into the TXT file by desired column, sorted and ranked. |
|**Origin**: Originates from our team wanting to ensure we provide the user with an accurate product |
|**Version**: 1.0 |
|**Date**: 11.30.2020 |
|**Priority**: 1 |

**Comment by GrantJonesWSU** [comment]
Appending Issue By 
[Uploading Sprint3.zip…]()

**Comment by GrantJonesWSU** [comment]
[Sprint3.zip](https://github.com/WSU-4110/Fantasy-Scout/files/5619195/Sprint3.zip)
