### ISSUE TITLE
FR9 Create a customizable profile

### ISSUE THREAD

**Issue by fr4800** [WSU-4110/Fantasy-Scout#14]
----------------------------------------------------------------------
| Create a customizable profile |
|---|
|**Goal**: The app will have a page where the user can change their username, biography, and profile picture from a set of given images |
|**Stakeholders**: For all users who have an account set up	|
|**Description**: From the home page the user can click on a button to customize their profile with a displayed username and profile picture. They can also add a 50 word or less biography about themselves |
|**Origin**: From a team meeting on how to create a user community |
|**Version**: 1.0 |
|**Date**:	9.24.2020 |
|**Priority**: 3 |
----------------------------------------------------------------------

**Comment by kevinWayneState** [comment]
In progress

**Comment by fr4800** [comment]
[customizeProfile.zip](https://github.com/WSU-4110/Fantasy-Scout/files/5622463/customizeProfile.zip)
Done in Sprint 3
