### ISSUE TITLE
FR4 Initialize SQL Database Structure

### ISSUE THREAD

**Issue by fr4800** [WSU-4110/Fantasy-Scout#19]
----------------------------------------------------------------------
| Data search, sort, and filter system |
|---|
|**Goal**: Create a data search, sort, and filter system |
|**Stakeholders**: Users of the application |
|**Description**: Users will be able to use the search, sort, and filtering system to refine by time, position, analyst and analyst company |
|**Origin**: Commonly used data search, sort, and filter systems (e.g. Stock Market apps, Fantasy Football apps, etc… |
|**Version**: 1.0 |
|**Date**:	9.24.2020	|
|**Priority**: 1 |
----------------------------------------------------------------------

**Comment by Joshperkey** [comment]
<img width="163" alt="Fantasy Scout Database Model" src="https://user-images.githubusercontent.com/43558775/95926569-9fa57200-0d8a-11eb-932e-019a77b1f274.png">
