### ISSUE TITLE
FR2 Settings Page

### ISSUE THREAD

**Issue by fr4800** [WSU-4110/Fantasy-Scout#21]
----------------------------------------------------------------------
| Settings Page |
|---|
|**Goal**: Create a settings page for basic app settings |
|**Stakeholders**: Users of the application |
|**Description**: There will be a settings page within the application for users to save, change, or delete certain settings (e.g. username, password, etc… |
|**Origin**:  Successful application modeling |
|**Version**: 1.0 |
|**Date**:	9.24.2020	|
|**Priority**: 2 |
----------------------------------------------------------------------

**Comment by kevinWayneState** [comment]
Light/Dark Theme Implemented
