### ISSUE TITLE
FR1.  Analyst Accuracy Algorithm

### ISSUE THREAD

**Issue by fr4800** [WSU-4110/Fantasy-Scout#22]
----------------------------------------------------------------------
| Analyst Accuracy Algorithm |
|---|
|**Goal**: Create an algorithm that calculates how accurate a fantasy football analyst’s ranking is to the actual performance rankings |
|**Stakeholders**:  Users of the app, fantasy football analysts, and the entire fantasy football community |
|**Description**: This is the most essential algorithm to the entire application.  This algorithm will take fantasy football analyst’s prediction rankings as input, compare it with the actual player performance rankings, and output the accuracy data |
|**Origin**:  Original IP |
|**Version**: 1.0 |
|**Date**:	9.24.2020	|
|**Priority**: 1 |
----------------------------------------------------------------------

**Comment by hmehryar** [comment]
Add "Feature" label to all requirements.
