### ISSUE TITLE
FR18. Create Scripts to Populate Database

### ISSUE THREAD

**Issue by Joshperkey** [WSU-4110/Fantasy-Scout#24]

**Comment by kevinWayneState** [comment]
- Kevin collected Fantasy Analyst Predictions Rankings for Weeks 1-6.  Grant is collecting Weeks 7-End of Season.
- Fantasy Analyst Prediction Rankings were delivered to Josh.
- Josh working on script to take .csv files and input into database.

**Comment by Joshperkey** [comment]
![positionsDB](https://user-images.githubusercontent.com/43558775/97911729-c287ce00-1d19-11eb-811d-5b288a227c02.png)
![teamsDB](https://user-images.githubusercontent.com/43558775/97911730-c287ce00-1d19-11eb-9554-9c5e61f7b014.png)
![organizationsDB](https://user-images.githubusercontent.com/43558775/97911731-c287ce00-1d19-11eb-8723-c0c1c9bde66d.png)

**Comment by Joshperkey** [comment]
this is done
