### ISSUE TITLE
FR22: File Management Script

### ISSUE THREAD

**Issue by GrantJonesWSU** [WSU-4110/Fantasy-Scout#26]
Goal: Create a script that automatically sorts downloaded data from fantasy predictions for reading into database

Stakeholders: Developers

Description: This takes the numerical format of the sources and data types downloaded in the crawler script and takes it into subsections of renamed and sorted data. Will directly be read by data reading algorithm and sorts for both user and machine reading.

Origin: Original IP

Version: 1.0

Date: 10.21.2020

Priority: 1

**Comment by kevinWayneState** [comment]
1. Developed the basic function to separate the files into source folder
2. Haven’t addressed renaming
3. Using system specific Windows Powershell ISE

**Comment by GrantJonesWSU** [comment]
##################################
#Variable Declaration
#################################

################################
#Variables to initialize
#################################
$weekNumber="8" #INITIALIZE TO THE CORRECT WEEK
$desktopPath = "C:\Users\jones\Desktop" #INITIALIZE WITH YOUR PATH TO COMPUTER DESKTOP HOMESCREEN
$dateOfDownload ="- 2020-10-27" #INITIALIZE STRING WITH YEAR-MONTH-DAY FORMAT
$tCode="T133" #INITIALIZE WITH TCODE GIVEN TO FILES >100 (ALL WILL BE SAME IF DOWNLOADED ON SAME DAY/SOURCE TIME)


$newPredictionFolder="\PredictionDataWeek "
$pathOfWeekName = $desktopPath+$newPredictionFolder+$weekNumber

#Analyst Source Pathname
$fanDuel="\Fanduel"
$draftKings="\DraftKings"
$yDaily="\Y! Daily"
$cbs="\CBS"
$espn="\ESPN"
$fanBall="\FanBall"
$rtDaily="\RTDaily"
$nffc="\NFFC"
$ffpc="\FFPC"
$bb10="\BB10"
$tdo="\TDO"
$cdm="\CDM"
$rtdm="\RTDM"
$fanTrax="\FanTrax"
$h2h="\H2H Weekly"

#table export name base
$fileBaseName ="tableExport"

#Number Declarations for Renaming Use 
$one=" (1)"
$two=" (2)"
$three=" (3)"
$four=" (4)"
$five=" (5)"
$six=" (6)"
$seven=" (7)"
$eight=" (8)"
$nine=" (9)"
$ten=" (10)"
$ten1=" (11)"
$ten2=" (12)"
$ten3=" (13)"
$ten4=" (14)"
$ten5=" (15)"
$ten6=" (16)"
$ten7=" (17)"
$ten8=" (18)"
$ten9=" (19)"
$2ten=" (20)"
$2ten1=" (21)"
$2ten2=" (22)"
$2ten3=" (23)"
$2ten4=" (24)"
$2ten5=" (25)"
$2ten6=" (26)"
$2ten7=" (27)"
$2ten8=" (28)"
$2ten9=" (29)"
$3ten=" (30)"
$3ten1=" (31)"
$3ten2=" (32)"
$3ten3=" (33)"
$3ten4=" (34)"
$3ten5=" (35)"
$3ten6=" (36)"
$3ten7=" (37)"
$3ten8=" (38)"
$3ten9=" (39)"
$4ten=" (40)"
$4ten1=" (41)"
$4ten2=" (42)"
$4ten3=" (43)"
$4ten4=" (44)"
$4ten5=" (45)"
$4ten6=" (46)"
$4ten7=" (47)"
$4ten8=" (48)"
$4ten9=" (49)"
$5ten=" (50)"
$5ten1x=" (51)"
$5ten2=" (52)"
$5ten3=" (53)"
$5ten4=" (54)"
$5ten5=" (55)"
$5ten6=" (56)"
$5ten7=" (57)"
$5ten8=" (58)"
$5ten9=" (59)"
$6ten=" (60)"
$6ten1=" (61)"
$6ten2=" (62)"
$6ten3=" (63)"
$6ten4=" (64)"
$6ten5=" (65)"
$6ten6=" (66)"
$6ten7=" (67)"
$6ten8=" (68)"
$6ten9=" (69)"
$7ten=" (70)"
$7ten1=" (71)"
$7ten2=" (72)"
$7ten3=" (73)"
$7ten4=" (74)"
$7ten5=" (75)"
$7ten6=" (76)"
$7ten7=" (77)"
$7ten8=" (78)"
$7ten9=" (79)"
$8ten=" (80)"
$8ten1=" (81)"
$8ten2=" (82)"
$8ten3=" (83)"
$8ten4=" (84)"
$8ten5=" (85)"
$8ten6=" (86)"
$8ten7=" (87)"
$8ten8=" (88)"
$8ten9=" (89)"
$9ten=" (90)"
$9ten1=" (91)"
$9ten2=" (92)"
$9ten3=" (93)"
$9ten4=" (94)"
$9ten5=" (95)"
$9ten6=" (96)"
$9ten7=" (97)"
$9ten8=" (98)"
$9ten9x=" (99)"
$tentenx=" (100)"
##############################################################


###################################
#Create New Folder On Computer Desktop
#####################################
#TO FORMAT TO YOUR OWN COMPUTER REPLACE PATH WITH THE DESKTOP PATH
#ON YOUR DEVICE WITH ONE ADDITIONAL LINE FOR THE NewPredictionData FOLDER
#AS SEEN IN EXISTING CODE
############################################
New-Item -Path $pathOfWeekName  -ItemType Directory #Folder To Hold New Prediction Data

######################################
#Populate Week# Prediction Data Folder with all downloaded data
#####################################
#MAKE SURE DOWNLOADS FOLDER ON YOUR COMPUTER IS EMPTY OF PDF FILES THAT AREN'T
#PREDICTION DATA
############################################
Get-ChildItem -Path "C:\Users\jones\Downloads" *tableExport*.pdf. -Recurse | Copy-Item -Destination $pathOfWeekName



########################################
#Analyst Source Folder Creation
#########################################
New-Item -Path $pathOfWeekName$fanDuel -ItemType Directory #Fanduel Folder
New-Item -Path $pathOfWeekName$draftKings -ItemType Directory #DraftKings Folder
New-Item -Path $pathOfWeekName$yDaily -ItemType Directory #Y!Daily Folder
New-Item -Path $pathOfWeekName$cbs -ItemType Directory #CBS Folder
New-Item -Path $pathOfWeekName$espn -ItemType Directory #ESPN Folder
New-Item -Path $pathOfWeekName$fanBall -ItemType Directory #H2H Weekly Folder
New-Item -Path $pathOfWeekName$rtDaily -ItemType Directory #RTDaily Folder
New-Item -Path $pathOfWeekName$nffc -ItemType Directory #NFFC Folder
New-Item -Path $pathOfWeekName$ffpc -ItemType Directory #FFPC Folder
New-Item -Path $pathOfWeekName$bb10 -ItemType Directory #BB10 Folder
New-Item -Path $pathOfWeekName$tdo -ItemType Directory #TDO Folder
New-Item -Path $pathOfWeekName$cdm -ItemType Directory #CDM Folder
New-Item -Path $pathOfWeekName$rtdm -ItemType Directory #RTDM Folder
New-Item -Path $pathOfWeekName$fanTrax -ItemType Directory #FanTrax Folder
New-Item -Path $pathOfWeekName$h2h -ItemType Directory #H2H Weekly Folder


#fanDuel Renaming & folder placement
Rename-Item $pathOfWeekName\$fileBaseName.pdf fanDuelQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$one.pdf fanDuelRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$two.pdf fanDuelWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$three.pdf fanDuelTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$four.pdf fanDuelFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$five.pdf fanDuelK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$six.pdf fanDuelDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$seven.pdf fanDuelIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$eight.pdf fanDuelDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$nine.pdf fanDuelLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten.pdf fanDuelDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*fanDuel*.pdf' | Move-Item -destination $pathOfWeekName$fanDuel

#draftKings
Rename-Item $pathOfWeekName\$fileBaseName$ten1.pdf draftKingsQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten2.pdf draftKingsRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten3.pdf draftKingsWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten4.pdf draftKingsTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten5.pdf draftKingsFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten6.pdf draftKingsK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten7.pdf draftKingsDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten8.pdf draftKingsIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$ten9.pdf draftKingsDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten.pdf draftKingsLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten1.pdf draftKingsDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*draftKings*.pdf' | Move-Item -destination $pathOfWeekName$draftKings

#yDaily
Rename-Item $pathOfWeekName\$fileBaseName$2ten2.pdf yDailyQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten3.pdf yDailyRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten4.pdf yDailyWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten5.pdf yDailyTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten6.pdf yDailyFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten7.pdf yDailyK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten8.pdf yDailyDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$2ten9.pdf yDailyIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten.pdf yDailyDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten1.pdf yDailyLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten2.pdf yDailyDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*yDaily*.pdf' | Move-Item -destination $pathOfWeekName$yDaily

#cbs
Rename-Item $pathOfWeekName\$fileBaseName$3ten3.pdf cbsQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten4.pdf cbsRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten5.pdf cbsWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten6.pdf cbsTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten7.pdf cbsFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten8.pdf cbsK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$3ten9.pdf cbsDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten.pdf cbsIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten1.pdf cbsDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten2.pdf cbsLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten3.pdf cbsDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*cbs*.pdf' | Move-Item -destination $pathOfWeekName$cbs

#espn
Rename-Item $pathOfWeekName\$fileBaseName$4ten4.pdf espnQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten5.pdf espnRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten6.pdf espnWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten7.pdf espnTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten8.pdf espnFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$4ten9.pdf espnK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten.pdf espnDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten1x.pdf espnIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten2.pdf espnDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten3.pdf espnLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten4.pdf espnDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*espn*.pdf' | Move-Item -destination $pathOfWeekName$espn

#fanBall
Rename-Item $pathOfWeekName\$fileBaseName$5ten5.pdf fanBallQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten6.pdf fanBallRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten7.pdf fanBallWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten8.pdf fanBallTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$5ten9.pdf fanBallFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten.pdf fanBallK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten1.pdf fanBallDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten2.pdf fanBallIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten3.pdf fanBallDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten4.pdf fanBallLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten5.pdf fanBallDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*fanBall*.pdf' | Move-Item -destination $pathOfWeekName$fanBall

#rtDaily
Rename-Item $pathOfWeekName\$fileBaseName$6ten6.pdf rtDailyQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten7.pdf rtDailyRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten8.pdf rtDailyWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$6ten9.pdf rtDailyTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten.pdf rtDailyFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten1.pdf rtDailyK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten2.pdf rtDailyDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten3.pdf rtDailyIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten4.pdf rtDailyDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten5.pdf rtDailyLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten6.pdf rtDailyDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*rtDaily*.pdf' | Move-Item -destination $pathOfWeekName$rtDaily

#nffc
Rename-Item $pathOfWeekName\$fileBaseName$7ten7.pdf nffcQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten8.pdf nffcRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$7ten9.pdf nffcWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten.pdf nffcTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten1.pdf nffcFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten2.pdf nffcK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten3.pdf nffcDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten4.pdf nffcIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten5.pdf nffcDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten6.pdf nffcLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten7.pdf nffcDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*nffc*.pdf' | Move-Item -destination $pathOfWeekName$nffc

#ffpc
Rename-Item $pathOfWeekName\$fileBaseName$8ten8.pdf ffpcQB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$8ten9.pdf ffpcRB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten.pdf ffpcWR.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten1.pdf ffpcTE.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten2.pdf ffpcFLEX.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten3.pdf ffpcK.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten4.pdf ffpcDST.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten5.pdf ffpcIDP.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten6.pdf ffpcDB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten7.pdf ffpcLB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$9ten8.pdf ffpcDL.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*ffpc*.pdf' | Move-Item -destination $pathOfWeekName$ffpc

#bb10
Rename-Item $pathOfWeekName\$fileBaseName$9ten9x.pdf bb10QB.pdf
Rename-Item $pathOfWeekName\$fileBaseName$tentenx.pdf bb10RB.pdf

Get-ChildItem $pathOfWeekName -recurse -filter '*bb10*.pdf' | Move-Item -destination $pathOfWeekName$bb10


$source = $pathOfWeekName
$destination = $pathOfWeekName

#REST OF bb10 WEIRD NAMING CONVENTIONS
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10WR.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10TE.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10FLEX.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10K.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10DST.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10IDP.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10DB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10LB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$bb10\bb10DL.pdf") -force} 
pause

#TDO
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoQB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoRB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoWR.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoTE.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoFLEX.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoK.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoDST.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoIDP.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoDB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoLB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$tdo\tdoDL.pdf") -force} 

#CDM
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmQB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmRB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmWR.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmTE.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmFLEX.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmK.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmDST.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmIDP.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmDB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmLB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$cdm\cdmDL.pdf") -force} 
pause

#RTDM
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmQB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmRB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmWR.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmTE.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmFLEX.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmK.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmDST.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmIDP.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmDB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmLB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$rtdm\rtdmDL.pdf") -force} 
pause

#FanTrax
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxQB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxRB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxWR.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxTE.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxFLEX.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxK.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxDST.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxIDP.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxDB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxLB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$fanTrax\fanTraxDL.pdf") -force} 
pause

#H2H Weekly
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hQB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hRB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hWR.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hTE.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hFLEX.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hK.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hDST.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hIDP.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hDB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hLB.pdf") -force} 
@(Get-ChildItem $source -Filter *.pdf | Sort CreationTime)[0] | % { Move-Item -path $_.FullName -destination $("$destination$h2h\h2hDL.pdf") -force} 

pause

**Comment by GrantJonesWSU** [comment]
Powershell ise file to be intialized as specified in comments and executed.  Automatically compiles files into folders and renames them
