### ISSUE TITLE
FR #23: Figure out Webpage Architecture in Atom

### ISSUE THREAD

**Issue by kevinWayneState** [WSU-4110/Fantasy-Scout#27]
Figure out Webpage Architecture in Atom

**Comment by kevinWayneState** [comment]
Because we're pivoting from mobile app to web app

**Comment by kevinWayneState** [comment]
Connecting to Atom IDE.
Pushing skeleton app today.
Note: Slightly behind due to pivot from Mobile App to Web App

**Comment by fr4800** [comment]
Pushed initial Web App Skeleton on 20.10.30
Still need to flesh out search and settings page. Still need to add login start page
