### ISSUE TITLE
NFR4 SYSTEM PERFORMANCE IN HIGH TRAFFIC

### ISSUE THREAD

**Issue by Joshperkey** [WSU-4110/Fantasy-Scout#3]
|**Goal**Ensure that the system remains functioning properly and as intended for any level of user traffic**:  |
|**Stakeholders**All users, analysts, and companies utilizing this app or that is affected by the use of this app will desire the app to function properly**:	| 
|**Description**:Ensure the app’s servers can handle the highest traffic that the app sees. If user traffic goes up and the system/servers cannot handle the high traffic, upgraded the servers or software to be able to handle more users**:	|
|**Origin**:The developers have agreed the system should be functional for any number of users**:	|
|**Version**:	1.0|
|**Date**:	9.27.20|
|**Priority**: 3|

**Comment by GrantJonesWSU** [comment]
Multiuser traffic can simultaneously access database stored information, they cannot interact w available information so no risk of overwriting or multiprogramming errors
