### ISSUE TITLE
FR26: User Account Login

### ISSUE THREAD

**Issue by Joshperkey** [WSU-4110/Fantasy-Scout#31]
Goal: Allow users with an already registered account to login into the web app
--
Stakeholders: Users of the application
Description: Once users have created an account, they can log in to access their settings.
Origin: Successful application modeling
Version: 1.0
Date: 9.24.2020
Priority: 2

**Comment by fr4800** [comment]
[login.txt](https://github.com/WSU-4110/Fantasy-Scout/files/5518540/login.txt)
