### ISSUE TITLE
FR 27: Convert Android skeleton app to HTML skeleton app

### ISSUE THREAD

**Issue by Joshperkey** [WSU-4110/Fantasy-Scout#32]
Goal: Since the project is being switched from an android app to a web application, the skeleton should be an HTML application.
--
Stakeholders: Developers
Description: To ease the burden on the developers, the skeleton app will be changed from being an android studio application to an HTML web application.
Origin: Successful application modeling
Version: 1.0
Date: 9.24.2020
Priority: 1

**Comment by fr4800** [comment]
[Fantasy-Scout-master.zip](https://github.com/WSU-4110/Fantasy-Scout/files/5518505/Fantasy-Scout-master.zip)
