### ISSUE TITLE
NFR3 EASE OF USE

### ISSUE THREAD

**Issue by Joshperkey** [WSU-4110/Fantasy-Scout#4]
|**Goal**:Ensure that users can quickly/easily find any information the app can provide**:  |
|**Stakeholders**:Users will desire quick and easy access**:	| 
|**Description**:The app interface should be coded in a way where it is very obvious and easy to get the specific information a user is interested in**:	|
|**Origin**:The development team would like to create an easy to use app to appeal to the most amount of users**:	|
|**Version**:	1.0|
|**Date**:	9.27.20|
|**Priority**: 2|

**Comment by fr4800** [comment]
Nonfunctional Requirement
