### ISSUE TITLE
FR16 Start menu and account UI

### ISSUE THREAD

**Issue by kevinWayneState** [WSU-4110/Fantasy-Scout#5]
| Start menu and account UI |
|---|
|**Goal**: The system will boot up to a simple UI that allows the user to proceed with logging in, creating a new account, or proceeding as a guest. |
|**Stakeholders**: Encompasses all users, allowing returning users with increased involvement to have better data protection. | 
|**Description**: When the application is booted up the user will be given a start menu allowing them to login, create an account, or proceed as a guest. Returning users will be remembered (optional) and the premise will provide substantial increase in returning user data security. |
|**Origin**: Based on the existing web interfaces and outlined in a team brainstorm session, the team decided this was an efficient and secure manner to accommodate return users	|
|**Version**: 1.0 |
|**Date**:	9.24.2020 |
|**Priority**: 1 |

**Comment by kevinWayneState** [comment]
In progress

**Comment by fr4800** [comment]
[menuStartUp.zip](https://github.com/WSU-4110/Fantasy-Scout/files/5622477/menuStartUp.zip)
Finished on Sprint 3
