### ISSUE TITLE
NFR2 EASE OF MAINTENANCE

### ISSUE THREAD

**Issue by Joshperkey** [WSU-4110/Fantasy-Scout#6]
|**Goal**:Build app in a way that changes can easily be made by the development team**:  |
|**Stakeholders**:Development team**:	| 
|**Description**:Ensure that if problems arise or the development team desires to add more functionality that it is very simple to build on the existing code. This will also make it easy for the development team to add support for more sports analyst websites to be analyzed.
|**Origin**:The development team would like the app to be easy to maintain:	|
|**Version**: 1.0|
|**Date**:	 9.27.20|
|**Priority**: 2|

**Comment by kevinWayneState** [comment]
In Progress.  UI updated.

**Comment by GrantJonesWSU** [comment]
Scripts for maintaining project are well commented and easy to access
