### ISSUE TITLE
FR15 Data collection variety and accuracy

### ISSUE THREAD

**Issue by kevinWayneState** [WSU-4110/Fantasy-Scout#7]
| Data collection variety and accuracy |
|---|
|**Goal**: TO provide data sets from at least 4 major analyst sources and to check the accuracy of our own data collection |
|**Stakeholders**: Affects all users by the quality of the information they receive. Affects developers by assuring the data set we provide is accurate and varied | 
|**Description**: We will compile data from at least 4 major source of fantasy football predictions and analytics and compare it against the weekly reports of actual reported scores, indexing analyst predictions against the actual outcome and reporting the variance	|
|**Origin**: Came from a team collaboration in app proposal stage in deciding how our application presents data	|
|**Version**: 1.0 |
|**Date**:	9.24.2020 |
|**Priority**: 2 |

**Comment by fr4800** [comment]
![image](https://user-images.githubusercontent.com/71450989/101391744-c36ccc00-3892-11eb-8677-a3e3583fa247.png)
