### ISSUE TITLE
NFR1 RELIABILITY OF DATA COLLECTION

### ISSUE THREAD

**Issue by Joshperkey** [WSU-4110/Fantasy-Scout#8]
|**Goal**:Ensure that the automatic collection of data from sports analysts websites is always correct**:  |
|**Stakeholders**:The dev team, the users, and the analysts analyzed will expect the app to have correct information 100% of the time**:	| 
|**Origin**:Having a data collection algorithm that is not 100% correct will diminish the reputation of the app and deter users from using the app**:	|
|**Version**: The development team would like to make a reliable app**:	|
|**Version**:	1.0|
|**Date**:	 9.27.20|
|**Priority**: 1|

**Comment by fr4800** [comment]
Nonfunctional requirement
